import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import { AuthContext, AuthProvider } from "./context/AuthContext";
import { BoardContextProvider } from "./context/BoardContext";
import { CartContextProvider } from "./context/CartContext"
import { Suspense, useContext, } from "react";
import Loading from "@/loading";
import Loader from "./components/Loader";
// import ReactDOMServer from 'react-dom/server';
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (

    <AuthProvider>
      <BoardContextProvider>
        <CartContextProvider>
          <html lang="en">
            <body className={inter.className} >
             <Loader/>
             {children}
            </body>
          </html>
        </CartContextProvider>
      </BoardContextProvider>
    </AuthProvider>


  );
}
