import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import { AuthProvider } from "./context/AuthContext";
import { BoardContextProvider } from "./context/BoardContext";
import { CartContextProvider } from "./context/CartContext"
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (

    <AuthProvider>
      <BoardContextProvider>
        <CartContextProvider>
          <html lang="en">
            <body className={inter.className}>
              {children}
            </body>
          </html>
        </CartContextProvider>
      </BoardContextProvider>
    </AuthProvider>


  );
}
